# Secret for accessing Application Metrics by Prometheus
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth
  namespace: argo-rollouts         # Must match the application namespace
type: Opaque
data:
  PROM_USER: cHJvbWV0aGV1cw==      # Base64-encoded "prometheus"
  PROM_PASS: c2VjdXJlcGFzc3dvcmQ=  # Base64-encoded "securepassword"
